version: "2"

services:

  client:
    image: webapp-client
    build:
      dockerfile: Dockerfile
      context: "./client"
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./api:/app
    links:
      - api
    command:
      - npm start

  api:
    image: webapp-api
    build:
      dockerfile: Dockerfile
      context: "./api"
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - mongodb
    command:
      - npm start

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth
